---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: fips-image-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/orchestrator-releng-tenant/orchestrator-operator-bundle@sha256:c24af5d0aa25b237838198903d31dd4585e4841bf9345e661e5638064580ccc2
      source: registry.stage.redhat.io/rhdh-orchestrator-dev-preview-beta/orchestrator-operator-bundle@sha256:c24af5d0aa25b237838198903d31dd4585e4841bf9345e661e5638064580ccc2