---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: fips-image-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/orchestrator-releng-tenant/orchestrator-operator-bundle
      source: registry.stage.redhat.io/rhdh-orchestrator-dev-preview-beta/orchestrator-operator-bundle
    - mirrors:
        - quay.io/redhat-user-workloads/orchestrator-releng-tenant/orchestrator-operator-bundle
      source: registry.redhat.io/rhdh-orchestrator-dev-preview-beta/orchestrator-operator-bundle